version: '3.0'

services:
  nl2sparql:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./T5_base/trained:/app/T5_base/trained
      - ./app.py:/app/app.py
    environment:
      - PYTHONUNBUFFERED=1
    container_name: nl2sparql_service
    hostname: nl2sparql-host
    restart: always
    networks:
      - nl2sparql_t5_network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok-nl2sparql
    restart: always
    environment:
      - NGROK_AUTHTOKEN=2vYIEAi19a7QihZjdxMG2ABRTp4_5PHERtFfK84tvikowvXdW
      - NGROK_REGION=Global
    command: ["http", "nl2sparql_service:5000", "--domain=deep-gator-cleanly.ngrok-free.app"]
    ports:
      - "4045:4040"  # Expose ngrok's web interface (optional)
    depends_on:
      - nl2sparql
    networks:
      - nl2sparql_t5_network

networks:
  nl2sparql_t5_network:
    driver: bridge