version: "3.0"
services:
  analytics_service:
    build:
      context: . # Project root containing app.py and Dockerfile
      dockerfile: Dockerfile
    container_name: analytics_service
    ports:
      - "6000:6000"
    networks:
      - my_bridge

networks:
  my_bridge:
